---
# Nginx system.
- name: Copy nginx configuration in place
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Remove default nginx vhost config file (if configured)
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost


- name: Add managed vhost config file (if any vhosts are configured)
  template:
    src: vhosts.conf.j2
    dest: "{{ nginx_vhost_path }}/vhosts_services.conf"
    mode: 0644
    #validate: "/usr/sbin/nginx -t -c %s"

- name: Ensure nginx is stopped
  service: name=nginx state=stopped

- name: Ensure nginx is started and enabled to start at boot
  service: name=nginx state=started enabled=yes
