---
- name: Install the php packages (APT)
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items: "{{ php_fpm_apt_packages }}"

- name: Copy the PHP configuration file
  ini_file: >
    dest={{ php_fpm_ini_path }}
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items: "{{ php_fpm_ini }}"

- name: Copy the FPM configuration
  ini_file: >
    dest={{ php_fpm_config_path }}
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items: "{{ php_fpm_config }}"
  register: copy_fpm_config

- name: Delete the include line from the ini file
  ini_file: >
    dest={{ php_fpm_config_path }}
    section=global
    option=include
    state=absent
    backup=no
  when: copy_fpm_config.changed

- name: Readd the include line to the ini file
  ini_file: >
    dest={{ php_fpm_config_path }}
    section=global
    option=include
    value="{{ php_fpm_pool_d }}/*.conf"
    state=present
    backup=no
  when: copy_fpm_config.changed

- name: Delete the default POOL configuration file
  file: >
    path={{ php_fpm_pool_d }}/{{ php_fpm_default_pool.name }}
    state=absent
  when: php_fpm_default_pool.delete

- name: Copy the POOL configurations
  template: >
    src=pool.conf.j2
    dest={{ php_fpm_pool_d }}/{{ item['name'] }}.conf
    backup=yes
  with_items: "{{ php_fpm_pools }}"
  when: php_fpm_pools|lower != 'none'

- name: Check php-fpm syntax of configuration files
  shell: "{{ php_fpm_binary_name }} -t"
  register: result
  changed_when: "result.rc != 0"

- name: Start the php-fpm service
  service: name={{ php_fpm_service_name }} state=restarted enabled=yes
