---
- hosts: hg
  remote_user: ansible
  become: yes
  roles:
     - hg

- hosts: git
  remote_user: ansible
  become: yes
  roles:
     - git

- hosts: php-cli
  remote_user: ansible
  become: yes
  roles:
    - php

- hosts: php-fpm
  remote_user: ansible
  become: yes
  roles:
    - php-fpm