---
- hosts: hg
  become: true
  roles:
     - hg

- hosts: git
  become: true
  roles:
     - git

- hosts: php-cli
  become: true
  roles:
    - php
  tags: php

- hosts: nginx
  become: true
  roles:
    - nginx
  tags: nginx

- hosts: php-fpm
  become: true
  roles:
    - php-fpm
  tags: php