---
- hosts: nginx-front
  remote_user: ansible
  become: true
  roles:
     - nginx-front

- hosts: nginx-front
  remote_user: ansible
  become: true
  roles:
     - nginx-restart

- hosts: php-fpm
  become: true
  roles:
    - php-fpm-restart