---

- name: MAKE | Check make file
  file:
    path: "{{ code_deploy_path }}/make.sh"
    mode: "+x"

- name: MAKE | MAKE
  shell: "{{ code_deploy_path }}/make.sh"
  args:
    chdir: "{{ code_deploy_path }}"
  become: yes
  become_user: "{{ rsync_user }}"

- name: MAKE | Move DEB
  shell: "mv {{ code_deploy_path }}/*.deb {{ code_base_path }}"
  args:
    chdir: "{{ code_deploy_path }}"
  become: yes
  become_user: "{{ rsync_user }}"

- name: MAKE | Clear deploy files
  file:
    state: absent
    path: "{{ code_deploy_path }}"

- name: Get list deb
  find:
    paths: "{{ code_base_path }}"
    patterns: "*.deb"
  become: yes
  register: debs

- fail:
    msg: "MAKE | Debian package not found"
  when: debs.files|length != 1

- name: Register debs
  set_fact:
    debs: "{{ debs.files }}"