---
- name: Get release version
  set_fact:
    release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: release_version is not defined
  delegate_to: 127.0.0.1
  become_user: ansible

- name: Get base service path
  set_fact: code_base_path="{{ releases_path }}/{{ service_name }}"

- name: Get release path
  set_fact: release_path="{{ code_base_path }}/releases/{{ release_version }}"

- name: Get release path
  set_fact: deploy_path="{{ code_base_path }}/deploy"

- name: Clear up directory to get code
  file:
    state: absent
    path: "{{ deploy_path }}"

- name: Creates directory to get code
  file:
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes

- name: Creates directory to release code
  file:
    path: "{{ release_path }}"
    state: directory
    recurse: yes

- include_tasks: "update-code/{{ deploy_via | default('git') }}.yml"

- name: Clearup deploy directory
  file:
    state: absent
    path: "{{ deploy_path }}"

# Performs symlink exchange
- name:  Change softlink to new release
  file:
    state: link
    force: yes
    path: "{{ code_base_path }}/{{ current_release_dir }}"
    src: "{{ release_path }}"

- name: Clean up releases
  shell: ls -1dt {{ code_base_path }}/releases/* | tail -n +{{ keep_releases | int + 1 }} | xargs rm -rf
  args:
    chdir: "/"
  when: keep_releases > 0
