---
php_fpm_ini_path: /etc/php5/fpm/php.ini
php_fpm_config_path: /etc/php5/fpm/php-fpm.conf
php_fpm_pool_d: /etc/php5/fpm/pool.d

php_fpm_binary_name: php5-fpm
php_fpm_service_name: php5-fpm

php_fpm_pid_file: /var/run/php5-fpm.pid


php_fpm_pool_defaults:
  pm: dynamic
  pm.max_children: 5
  pm.start_servers: 2
  pm.min_spare_servers: 1
  pm.max_spare_servers: 3

php_fpm_apt_packages:
  - php5-fpm
  - php5-pgsql

php_fpm_default_pool:
  delete: yes
  name: www.conf
