
php_fpm_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "ldap.max_links"
   section: "ldap"
   value: "1"

php_fpm_config:
 - option: "error_log"
   section: "global"
   value: "/var/log/php5-fpm.log"
