---
- hosts:
    front_app
    services
  become: true
  roles:
     - code-rollback

- hosts: php-fpm
  become: true
  roles:
    - php-fpm-restart

- hosts: nginx
  become: true
  roles:
    - nginx-reload